# Generated by Django 5.0.4 on 2024-06-20 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('status', models.CharField(choices=[('CP', 'Completed'), ('IP', 'In Progress'), ('NS', 'Not Started'), ('FA', 'Failed')], max_length=2)),
            ],
        ),
    ]
